spring:
  application:
    name: springapigateway
  config:
    import: optional:configserver:http://localhost:8888
  redis:
    host: localhost
    port: 6379
  cloud:
    gateway:
      routes:
        - id: interview-service
          uri: lb://INTERVIEWPREP
          predicates:
            - Path=/employee/**,/user/**
          filters:
            - name: CircuitBreaker
              args:
                name: interview-service
                fallbackUri: forward:/fallback
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 1
                redis-rate-limiter.requestToken: 1
        - id: microservice
          uri: lb://MICROSERVICEAPP
          predicates:
              - Path=/ms/**
          filters:
            - name: CircuitBreaker
              args:
                name: microservice
                fallbackUri: forward:/fallback
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 1
                redis-rate-limiter.requestToken: 1
server:
  port: 8082